
/**
 * 
 * @class
 * Example of Controller
 * 
 * @param {View} View
 * @param {Array} Arguments
 * @param {Logger} Logger
 * 
 */
var Controller = function(View, Arguments, Logger){

	/// injected instance of the controller
	Logger.info("init");

	View.index.open();

};

/**
 *
 * The controller dependencies.
 * 
 * @type {Array}
 * 
 */
Controller.$inject = [ "View", "Arguments", "Logger" ];


///
/// This part exports the Controller instance with IOC enabled.
///
/// The code generated by Alloy doesn't give you much choice. See example bellow:
/// https://gist.github.com/aetheon/7cd64e530cfaf1bb579b#file-alloy-controller
///
var ControllerFactory = require("/ControllerFactory");
module.exports = ControllerFactory.create(Controller, $, arguments);
